default_language_version:
  python: python3
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
    rev: "v0.0.267"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --line-length=120 ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
        - id: pyupgrade
          args: [--py3-plus]