# Generated by Django 4.1 on 2022-08-22 11:13

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.news.models.upload_to),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
