# Generated by Django 4.1 on 2022-08-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.DeleteModel(
            name='NewsAttachment',
        ),
    ]
