# Generated by Django 4.1 on 2022-08-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_attachment_type_delete_newsattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='owner',
        ),
    ]
